### ISSUE TITLE
templatePath is invalid on a Mac

### ISSUE THREAD

**Issue by frankprogrammer** [alexa/skill-sample-nodejs-web-api-my-cactus#17]
Working from the joeDev branch,

ask deploy gives the error:
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": Error: ENOENT: no such file or directory, open '.\infrastructure\cfn-deployer\skill-stack.yaml'

In ask-resources.json this line does not work on a Mac
"templatePath": ".\\infrastructure\\cfn-deployer\\skill-stack.yaml"

If I change it to this it works fine:
"templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml"

I am not sure if this change will work on Windows.

**Comment by SleepyDeveloper** [comment]
Thanks for bringing this up. I ran into this issue on stream today. @JoeMoCode and I will have to put our heads together to solve this one.

**Comment by LetMyPeopleCode** [comment]
@SleepyDeveloper Windows will accept forward slashes in paths.

**Comment by JoeMoCode** [comment]
Thanks for raising this! Pushed fix for it.

**Comment by JoeMoCode** [comment]
Should be working now! tested your change, Frank, on Windows.
