### ISSUE TITLE
On physical device UI looks different then inside a web app

### ISSUE THREAD

**Issue by Vorob-Astronaut** [alexa/skill-sample-nodejs-web-api-my-cactus#23]
on a physical device echo-3 it looks like this

![telegram-cloud-photo-size-2-5213378291006812083-y](https://user-images.githubusercontent.com/5957210/96350805-32624b80-10c0-11eb-9083-3bca770a4d6d.jpg)

how can I make it in 3d as in a web app?

**Comment by JoeMoCode** [comment]
This is the static loading screen. It looks like the web application failed to initialize and is hanging. Try pulling the latest code!

Note, once you do get past this, the lighting will be off on this device. I still need to fix the Shader bug. Issue #4 here: https://developer.amazon.com/en-US/docs/alexa/web-api-for-games/known-issues.html#known-issues

**Comment by JoeMoCode** [comment]
I think I realized my mistake on this repo. I am missing an instruction. Before uploading, you must build the project to properly webpack the main.js file. From this screenshot, it looks like none of the JS for the game is being properly initialized. 

To fix, go to the webapp directory. Then, run "npm run build". Afterwards, do the upload.

I hope this helps! Please, let me know.
